#!/bin/bash

./qwirkle.exe --e2etest --hand-size=10 < ./tests/starting-hand/test.input > ./qwirkle.out
if diff -w ./tests/starting-hand/test.output ./qwirkle.out; then
    echo "Test passed"
else
    echo "Test failed"
fi