#!/bin/bash

./qwirkle.exe --e2etest --colour < ./tests/colour/test.input > ./qwirkle.out
if diff -w ./tests/colour/test.output ./qwirkle.out; then
    echo "Test passed"
else
    echo "Test failed"
fi