#!/bin/bash

./qwirkle.exe --e2etest --mp < ./tests/multiplayer/test.input > ./qwirkle.out
if diff -w ./tests/multiplayer/test.output ./qwirkle.out; then
    echo "Test passed"
else
    echo "Test failed"
fi