#!/bin/bash

echo "Running credits test"
./tests/credits/test &&
echo "Running load-game test"
./tests/load-game/test &&
echo "Running new-game test"
./tests/new-game/test &&
echo "Running save-game test"
./tests/save-game/test &&
echo "Running game-end test"
./tests/game-end/test &&
echo "Running qwirkle test"
./tests/qwirkle/test &&
echo "Running line-validation test"
./tests/line-validation/test;
echo "Running multiplayer test"
./tests/multiplayer/test;
echo "Running AI test"
./tests/ai/test;
echo "Running colour test"
./tests/colour/test;
echo "Running board-resize test"
./tests/board-size/test;
echo "Running starting-hand test"
./tests/starting-hand/test;