#!/bin/bash

./qwirkle.exe --e2etest --board-size=10x20 < ./tests/board-size/test.input > ./qwirkle.out
if diff -w ./tests/board-size/test.output ./qwirkle.out; then
    echo "Test passed"
else
    echo "Test failed"
fi