#!/bin/bash

./qwirkle.exe --e2etest < ./tests/save-game/test.input > ./qwirkle.out
if ! diff -w ./tests/save-game/test.output ./qwirkle.out > /dev/null; then
    echo "Test failed: Difference found in test.output and qwirkle.out"
    diff -w ./tests/save-game/test.output ./qwirkle.out
else
    if [ -e ./tests/save-game/test.expsave ]; then 
        if ! diff -w ./tests/save-game/test.expsave ./tests/save-game/savedGame.txt > /dev/null; then
            echo "Test failed: Difference found in test.expsave and savedGame.txt"
            diff -w -y ./tests/save-game/test.expsave ./tests/save-game/savedGame.txt
        else
            echo "Test Passed"
        fi
    else
        echo "Expected save file does not exist"
    fi
fi