#!/bin/bash

./qwirkle.exe --e2etest < ./tests/line-validation/test.input > ./qwirkle.out
if diff -w ./tests/line-validation/test.output ./qwirkle.out; then
    echo "Test passed"
else
    echo "Test failed"
fi